import './globals.css'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AnyAppX - AI-Generated Mobile Apps',
  description: 'Portfolio of mobile apps generated by AnyAppX AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">{children}</body>
    </html>
  )
}
